# Generated by Django 6.0.7 on 2026-07-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_categories_courses_enrollments_user_enrollments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='student', max_length=50),
        ),
    ]
