# Generated by Django 6.0.7 on 2026-07-16 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer')], default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='courses',
            name='lecturer',
            field=models.ForeignKey(limit_choices_to={'roles': 'lecturer'}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
