# Generated by Django 6.0.7 on 2026-07-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_role_user_roles_alter_courses_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='number_of_lectures',
            field=models.PositiveIntegerField(default=0, help_text='Number of lecture entries to create for this course'),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_number', models.PositiveIntegerField(default=1)),
                ('lecture_name', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='course_lectures/pdfs/')),
                ('meeting_link', models.URLField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='base.courses')),
            ],
            options={
                'ordering': ['lecture_number'],
                'unique_together': {('course', 'lecture_number')},
            },
        ),
    ]
