# Generated by Django 6.0.7 on 2026-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_courses_number_of_lectures_lecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['lecture_number'], 'verbose_name': 'Lecture', 'verbose_name_plural': 'Lectures'},
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_description',
            field=models.TextField(blank=True),
        ),
    ]
