# Generated by Django 6.0.7 on 2026-08-09 17:21

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_lecture_options_lecture_lecture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdfs/'),
        ),
    ]
